"""create applications table

Revision ID: 71659dc364f1
Revises: 
Create Date: 2025-12-29 12:46:49.384765

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71659dc364f1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('job_title', sa.String(length=255), nullable=False),
    sa.Column('job_company', sa.String(length=255), nullable=False),
    sa.Column('job_location', sa.String(length=255), nullable=True),
    sa.Column('job_url', sa.Text(), nullable=True),
    sa.Column('resume_filename', sa.String(length=255), nullable=True),
    sa.Column('resume_text', sa.Text(), nullable=False),
    sa.Column('job_description', sa.Text(), nullable=False),
    sa.Column('questions', sa.Text(), nullable=True),
    sa.Column('fit_score', sa.Integer(), nullable=True),
    sa.Column('fit_level', sa.String(length=50), nullable=True),
    sa.Column('fit_reasons', sa.Text(), nullable=True),
    sa.Column('fit_gaps', sa.Text(), nullable=True),
    sa.Column('job_parsed_markdown', sa.Text(), nullable=True),
    sa.Column('tailored_resume_md', sa.Text(), nullable=True),
    sa.Column('cover_letter', sa.Text(), nullable=True),
    sa.Column('qna', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('applications')
    # ### end Alembic commands ###
